<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Christliche Gemeinschaft Ellmendingen</title><link rel="icon" type="image/svg+xml" href="../assets/image/favicon.svg?v=b989e2e6a4966bee84f84b88aa97283e"><link href="../assets/css/style.css?v=e436b7ec2daeb0e18ed7be498ea2741a" rel="stylesheet" type="text/css"></head><body> <?php
    date_default_timezone_set('Europe/Berlin');
    $datum = date('Y-m-d');
    $heute = time();
  ?> <section class="form-style-5"><div class=""><h3>Warum diese Schulung?</h3><p>Wir haben in unserer (gastfreundlichen) Gemeinde eine tolle Küche und einen super Bistrobereich. Sehr viele Personen agieren hier und tragen dazu bei, dass wir die Gastfreundlichkeit (er)leben. Wir stellen jedoch auch fest, dass der Umgang mit den Geräten und die Kenntnis über eine Grundhygiene und Regelungen häufig nicht bekannt sind. So wird das Miteinander manchmal zur Herausforderung. Dem begegnen wir nun mit diesem Schulungs-Angebot.</p><h3>Wir haben das Ziel:</h3><p>Mind. 80% aller Personen, die in der Küche oder im Bistrobereich agieren, können bis Ende 2022 die Geräte bedienen und kennen die grundlegenden hygienischen Anforderungen sowie die Regelungen in der CG im Bereich Küche und Bistro. Ab Januar 2023 agieren nur noch eingewiesene Personen im Bistro- und Küchenbereich.</p><h3>Vorgehen:</h3><p>Es finden nach dem Gottesdienst um 12 Uhr ca. 45-60 minütliche Schulungen für max. 15 Personen statt. Anmeldung über die Website der CG.</p><h3>Termine:</h3><p>Jeden Sonntag um 12 Uhr, ab 3. Juli bis 18. Dezember (auch an den Sonntagen mit Familien-Gottesdienst)</p></div></section><section class="contact-form form-style-5"><h2>Anmeldung</h2><h3>Küchenschulung</h3><p class="results">Teilnehmer sind auf 15 pro Termin beschränkt.</p><form id="formular"><input name="Anmeldung" type="hidden" value="Küchenschulung"><div class="input-group"><label for="name">Nachname*</label> <input id="name" name="Nachname" type="text" pattern="[A-Za-z0-9-_äëïöüÄËÏÖÜßàéèîôûÀÉÈÎÔÛ\s]*" required> <label for="vorname">Vorname*</label> <input id="vorname" name="Vorname" type="text" pattern="[A-Za-z0-9-_äëïöüÄËÏÖÜßàéèîôûÀÉÈÎÔÛ\s]*" required></div><div class="input-group"><label for="email">E-Mail*</label> <input id="email" name="Mail" type="email" placeholder="beispiel@mail.de" required></div> <?php 
        $date01 = "2022-07-03";
        $date02 = "2022-07-10";
        $date03 = "2022-07-17";
        $date04 = "2022-07-24";
        $date05 = "2022-07-31";
        $date06 = "2022-08-07";
        $date07 = "2022-08-14";
        $date08 = "2022-08-21";
        $date09 = "2022-08-28";
        $date10 = "2022-09-04";
        $date11 = "2022-09-11";
        $date13 = "2022-09-25";
        $date15 = "2022-10-09";
        $date16 = "2022-10-16";
        $date17 = "2022-10-23";
        $date18 = "2022-10-30";
        $date19 = "2022-11-06";
        $date20 = "2022-11-13";
        $date21 = "2022-11-20";
        $date22 = "2022-11-27";
        $date23 = "2022-12-04";
        $date24 = "2022-12-11";
        $date25 = "2022-12-18";
        $jdate01 = strtotime($date01);
        $jdate02 = strtotime($date02);
        $jdate03 = strtotime($date03);
        $jdate04 = strtotime($date04);
        $jdate05 = strtotime($date05);
        $jdate06 = strtotime($date06);
        $jdate07 = strtotime($date07);
        $jdate08 = strtotime($date08);
        $jdate09 = strtotime($date09);
        $jdate10 = strtotime($date10);
        $jdate11 = strtotime($date11);
        $jdate13 = strtotime($date13);
        $jdate15 = strtotime($date15);
        $jdate16 = strtotime($date16);
        $jdate17 = strtotime($date17);
        $jdate18 = strtotime($date18);
        $jdate19 = strtotime($date19);
        $jdate20 = strtotime($date20);
        $jdate21 = strtotime($date21);
        $jdate22 = strtotime($date22);
        $jdate23 = strtotime($date23);
        $jdate24 = strtotime($date24);
        $jdate25 = strtotime($date25);
    ?> <div class="input-group"><label for="termin">Termin</label> <select id="termin" name="Termin"><option id="t00" value="">&nbsp;</option><option value="<?php echo $date01; ?>" id="t01">03.07.</option><option value="<?php echo $date02; ?>" id="t02">10.07.</option><option value="<?php echo $date03; ?>" id="t03">17.07.</option><option value="<?php echo $date04; ?>" id="t04">24.07.</option><option value="<?php echo $date05; ?>" id="t05">31.07.</option><option value="<?php echo $date06; ?>" id="t06">07.08.</option><option value="<?php echo $date07; ?>" id="t07">14.08.</option><option value="<?php echo $date08; ?>" id="t08">21.08.</option><option value="<?php echo $date09; ?>" id="t09">28.08.</option><option value="<?php echo $date10; ?>" id="t10">04.09.</option><option value="<?php echo $date11; ?>" id="t11">11.09.</option><option value="<?php echo $date13; ?>" id="t13">25.09.</option><option value="<?php echo $date15; ?>" id="t15">09.10.</option><option value="<?php echo $date16; ?>" id="t16">16.10.</option><option value="<?php echo $date17; ?>" id="t17">23.10.</option><option value="<?php echo $date18; ?>" id="t18">30.10.</option><option value="<?php echo $date19; ?>" id="t19">06.11.</option><option value="<?php echo $date20; ?>" id="t20">13.11.</option><option value="<?php echo $date21; ?>" id="t21">20.11.</option><option value="<?php echo $date22; ?>" id="t22">27.11.</option><option value="<?php echo $date23; ?>" id="t23">04.12.</option><option value="<?php echo $date24; ?>" id="t24">11.12.</option><option value="<?php echo $date25; ?>" id="t25">18.12.</option></select></div><hr><div class="input-group"><label for="datenschutz"><b>Datenschutz*</b></label><div class="ds_checkbox"><input id="datenschutz" name="Datenschutz" type="checkbox" value="eingewilligt" required></div><div class="ds_text"><span class="datenschutz">Hiermit willige ich nach Art. 7 MV-DSO ein, dass meine Daten in dem Kontext der Anmeldung zur Küchenschulung für gemeindeinterne Zwecke gespeichert und elektronisch verarbeitet werden. Unsere Datenschutzerklärung kann hier eingesehen werden: <a href="https://info.cg-ellmendingen.de/datenschutz">https://info.cg-ellmendingen.de/datenschutz</a></span></div></div><input class="confirm" name="Confirm" type="checkbox" tabindex="-1" autocomplete="do-not-autofill"> <label>Alle Angaben richtig? Dann los!</label> <input id="senden" type="submit"></form></section> <?php 
    $file = file_get_contents("https://w18web2.uber.space/cockpit-master/api/forms/export/kuechenschulung?token=7410582333ed2e6cf13a18025da827");
    $result01 = substr_count ( $file, $date01);
    $result02 = substr_count ( $file, $date02);
    $result03 = substr_count ( $file, $date03);
    $result04 = substr_count ( $file, $date04);
    $result05 = substr_count ( $file, $date05);
    $result06 = substr_count ( $file, $date06);
    $result07 = substr_count ( $file, $date07);
    $result08 = substr_count ( $file, $date08);
    $result09 = substr_count ( $file, $date09);
    $result10 = substr_count ( $file, $date10);
    $result11 = substr_count ( $file, $date11);
    $result13 = substr_count ( $file, $date13);
    $result15 = substr_count ( $file, $date15);
    $result16 = substr_count ( $file, $date16);
    $result17 = substr_count ( $file, $date17);
    $result18 = substr_count ( $file, $date18);
    $result19 = substr_count ( $file, $date19);
    $result20 = substr_count ( $file, $date20);
    $result21 = substr_count ( $file, $date21);
    $result22 = substr_count ( $file, $date22);
    $result23 = substr_count ( $file, $date23);
    $result24 = substr_count ( $file, $date24);
    $result25 = substr_count ( $file, $date25);
  ?> <script>if (<?php echo json_encode($result01); ?> >=15) document.getElementById("t01").disabled = true;
    if (<?php echo json_encode($result02); ?> >=15) document.getElementById("t02").disabled = true;
    if (<?php echo json_encode($result03); ?> >=15) document.getElementById("t03").disabled = true;
    if (<?php echo json_encode($result04); ?> >=15) document.getElementById("t04").disabled = true;
    if (<?php echo json_encode($result05); ?> >=15) document.getElementById("t05").disabled = true;
    if (<?php echo json_encode($result06); ?> >=15) document.getElementById("t06").disabled = true;
    if (<?php echo json_encode($result07); ?> >=15) document.getElementById("t07").disabled = true;
    if (<?php echo json_encode($result08); ?> >=15) document.getElementById("t08").disabled = true;
    if (<?php echo json_encode($result09); ?> >=15) document.getElementById("t09").disabled = true;
    if (<?php echo json_encode($result10); ?> >=15) document.getElementById("t10").disabled = true;
    if (<?php echo json_encode($result11); ?> >=15) document.getElementById("t11").disabled = true;
    if (<?php echo json_encode($result13); ?> >=15) document.getElementById("t13").disabled = true;
    if (<?php echo json_encode($result15); ?> >=15) document.getElementById("t15").disabled = true;
    if (<?php echo json_encode($result16); ?> >=15) document.getElementById("t16").disabled = true;
    if (<?php echo json_encode($result17); ?> >=15) document.getElementById("t17").disabled = true;
    if (<?php echo json_encode($result18); ?> >=15) document.getElementById("t18").disabled = true;
    if (<?php echo json_encode($result19); ?> >=15) document.getElementById("t19").disabled = true;
    if (<?php echo json_encode($result20); ?> >=15) document.getElementById("t20").disabled = true;
    if (<?php echo json_encode($result21); ?> >=15) document.getElementById("t21").disabled = true;
    if (<?php echo json_encode($result22); ?> >=15) document.getElementById("t22").disabled = true;
    if (<?php echo json_encode($result23); ?> >=15) document.getElementById("t23").disabled = true;
    if (<?php echo json_encode($result24); ?> >=15) document.getElementById("t24").disabled = true;
    if (<?php echo json_encode($result25); ?> >=15) document.getElementById("t25").disabled = true;</script><script>if (<?php echo $jdate01; ?> < <?php echo $heute; ?>) document.getElementById("t01").disabled = true;
    if (<?php echo $jdate01; ?> < <?php echo $heute; ?>) document.getElementById("t01").disabled = true;
    if (<?php echo $jdate02; ?> < <?php echo $heute; ?>) document.getElementById("t02").disabled = true;
    if (<?php echo $jdate03; ?> < <?php echo $heute; ?>) document.getElementById("t03").disabled = true;
    if (<?php echo $jdate04; ?> < <?php echo $heute; ?>) document.getElementById("t04").disabled = true;
    if (<?php echo $jdate05; ?> < <?php echo $heute; ?>) document.getElementById("t05").disabled = true;
    if (<?php echo $jdate06; ?> < <?php echo $heute; ?>) document.getElementById("t06").disabled = true;
    if (<?php echo $jdate07; ?> < <?php echo $heute; ?>) document.getElementById("t07").disabled = true;
    if (<?php echo $jdate08; ?> < <?php echo $heute; ?>) document.getElementById("t08").disabled = true;
    if (<?php echo $jdate09; ?> < <?php echo $heute; ?>) document.getElementById("t09").disabled = true;
    if (<?php echo $jdate10; ?> < <?php echo $heute; ?>) document.getElementById("t10").disabled = true;
    if (<?php echo $jdate11; ?> < <?php echo $heute; ?>) document.getElementById("t11").disabled = true;
    if (<?php echo $jdate13; ?> < <?php echo $heute; ?>) document.getElementById("t13").disabled = true;
    if (<?php echo $jdate15; ?> < <?php echo $heute; ?>) document.getElementById("t15").disabled = true;
    if (<?php echo $jdate16; ?> < <?php echo $heute; ?>) document.getElementById("t16").disabled = true;
    if (<?php echo $jdate17; ?> < <?php echo $heute; ?>) document.getElementById("t17").disabled = true;
    if (<?php echo $jdate18; ?> < <?php echo $heute; ?>) document.getElementById("t18").disabled = true;
    if (<?php echo $jdate19; ?> < <?php echo $heute; ?>) document.getElementById("t19").disabled = true;
    if (<?php echo $jdate20; ?> < <?php echo $heute; ?>) document.getElementById("t20").disabled = true;
    if (<?php echo $jdate21; ?> < <?php echo $heute; ?>) document.getElementById("t21").disabled = true;
    if (<?php echo $jdate22; ?> < <?php echo $heute; ?>) document.getElementById("t22").disabled = true;
    if (<?php echo $jdate23; ?> < <?php echo $heute; ?>) document.getElementById("t23").disabled = true;
    if (<?php echo $jdate24; ?> < <?php echo $heute; ?>) document.getElementById("t24").disabled = true;
    if (<?php echo $jdate25; ?> < <?php echo $heute; ?>) document.getElementById("t25").disabled = true;</script><script src="../assets/js/kuechenschulung.js?v=347bc389cdbf9d0fc3e44ec77042a6a6"></script></body></html>